# Generated by Django 5.1.7 on 2025-03-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('PreferNotToSay', 'Prefer not to say')], max_length=20)),
                ('faculty', models.CharField(max_length=50)),
                ('batch_year', models.CharField(max_length=4)),
                ('major', models.CharField(max_length=100)),
                ('skills', models.CharField(max_length=100)),
                ('why_join', models.TextField()),
                ('province', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('municipality', models.CharField(max_length=100)),
                ('consent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
